#!/bin/bash

usage()
{
 echo "program is running"  
}

checkRoot()
{
  userid=$(id -u)
  echo "The current user is: $(whoami)"

  if [ "$userid" -eq 0 ]; then
    echo "You are logged in as root" 
  else 
    echo "$(whoami) is not root"
    echo "You must be root to execute this program" 
    exit 1 
  fi

}




#MAIN

PROGNAME="$basename"$0")" 

checkRoot

if [ -e "$1" ]; then 
 for user in $(cat "$1"| cut -d"@" -f 1); 
  do echo  $user;  
     password=$(openssl rand -base64 10);   
     echo $password
     $(useradd $user -m -p $(openssl passwd -1 $password) -s /bin/bash);
     chage -d 0 $user;
     usermod -a -G CSI230 $user;  
 done
else 
  echo "File ${1} does not exist. Please use a different file." 
fi 



echo " " 
echo " " 
usage

